# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

home_redirect:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: /cms/simple
        permanent: true # this for 301

static:
    pattern: /{_locale}/static
    defaults:
        _controller: AcmeMainBundle:Demo:static
    requirements:
        _locale: fr|nl

cmf_create_rest:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

cmf_create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

block_cache:
    resource: "@CmfBlockBundle/Resources/config/routing/cache.xml"
    prefix: /

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
